# This is the main configuration file for Jekyl tha is applied
# for the entire website.

# Site settings
title: I'm Alex Dev Portofolio
email: aleximbrea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is ment to serve as a personal portfolio for my
  developing work. Also this offers a comprehensive presentation
  of my skill and useful contact details.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imalex.me" # the base hostname & protocol for your site
github_username:  AlexImb

# Build settings
markdown: kramdown
